### ISSUE TITLE
inconsistent alignment of column headers & spanners

### ISSUE THREAD

**Issue by bzkrouse** [GSK-Biostatistics/tfrmt#103]
![image](https://user-images.githubusercontent.com/14199771/171676230-474eb310-b92b-4c32-8261-e6a918dd4167.png)

Seems that spanners are center aligned and lower level labels are left aligned. Behavior is independent of col_align_plan

**Comment by statasaurus** [comment]
We need to check if we can add col_aligns to fix this.

**Comment by thebioengineer** [comment]
This is how you center the column labels. Can someone add this to the gt styling portion of our code?

```r
library(gt)

 gtcars %>%
    gt() %>% 
    tab_style(
      style = cell_text(align = "center"),
      locations = cells_column_labels()
   )
```

**Comment by karima662** [comment]
Proposed addition to print_to_gt
```r
gtcars %>%
  slice (1:4) %>%
  gt() %>% 
  tab_style(
    style = list(
      cell_text(whitespace = "pre", align = "center")
    ),
    locations = list(cells_column_labels())
  )

```
