### ISSUE TITLE
refactor table styling 

### ISSUE THREAD

**Issue by bzkrouse** [GSK-Biostatistics/tfrmt#108]
- provide additional table style options for print_to_gt
- define our defaults in gt_styles.R

**Comment by statasaurus** [comment]
I agree with the making of default gt styling, buit I am don't think we want to own additional table styles (beyond maybe fonts). Cause I want to see how much functionality we can keep in gt while still meeting our basic needs. Anything advanced people should go to gt. I think GT is also still a bit young there is a risk that Rich will change stuff and break out package
