### ISSUE TITLE
Helper function to convert tfrmt to a layerable template

### ISSUE THREAD

**Issue by bzkrouse** [GSK-Biostatistics/tfrmt#119]

**Comment by statasaurus** [comment]
I think I need more context for this cause I don't understand

**Comment by statasaurus** [comment]
In this case you should already be able to layer my_tfmrt1 and my_tfmrt2. Because it will always override the latest if you want to use one of these as a template then you can use just need to pipe that into a tfrmt and then write over the title and footnotes etc...
