### ISSUE TITLE
Readme - minor comments

### ISSUE THREAD

**Issue by bailliem** [GSK-Biostatistics/tfrmt#186]
Here are a couple of minor comments from reviewing the readme

* Spell out or explain what QC i.e. quality control. I think this is an important concept to motivate ARD, for example it enables simpler verification as results are stored in a machine readable format. $
* Link to a ARD reference. The best I could find is the 360 white paper or supporting [presentations](https://www.pharmasug.org/download/sde/rtp2021/PharmaSUG-NCSDE_2021-08.pdf)
* Could you add something around the ARD format for your example data sets. What the columns are, is there a controlled vocabulary, etc.  This would help connect to the functions and the expectations for ARD.

**Comment by statasaurus** [comment]
- For 1, do as stated above 
- for 2 just add the link saying go here for more information on ARDs
- Just add a link to the example were this is solved
