### ISSUE TITLE
Extend group concept to handle comparisons 

### ISSUE THREAD

**Issue by bailliem** [GSK-Biostatistics/tfrmt#187]
I might have missed this, but do you have any plans to store and process treatment comparisons similar to how you are handling treatment arms as a grouping variable?

For example, the efficacy data example `group` handles visit and treatment comparison jointly. `column` then stores the treatment arm, but then you need to make a decision on how to also model the comparison. In the current example the higher dose stores also the treatment comparison e.g. see row 56 of the data set. 

If you could extend the data model to store the type of analysis i.e. within treatment description or a treatment comparison, this could offer more flexibility. The type variable models the type of statistics i.e.

| group |type | label | column | param | value |  
| ------------- |------------- | ------------- |------------- | ------------- | ------------- |
|baseline | description | Mean | Placebo | mean | 79.0 | 
|baseline | description | Standard deviation | Placebo | SD | 5.0 | 
|Primary analysis | trt comparison | Week 12 analysis | TRT - PBO | LM mean | -0.3 | 
|Primary analysis | trt comparison | Week 12 analysis | TRT - PBO | LM stderr | 0.4 | 

This would allow you to handle tables or figures where you may want to sure treatment summaries and treatment differences on the same row i.e. like [here](https://www.nejm.org/doi/full/10.1056/NEJMc2205276)

**Comment by statasaurus** [comment]
I am not sure I understand what you are asking for here. If you look at the demography example we do something kind of like this. There are multiple grouping variables (`rowlbl1` and `grp`). This allows group specific formatting, in the case of demography a space after every group, but shared group labels. Using the data provided I tweaked things just a little bit, but generally it would look like this

```{r}
data <- tribble(
~group,	~type,	~label,	~column,	~param,	~value,
"baseline",	"description",	"Mean",	"Placebo",	"mean",	79.0,
"baseline",	"description",	"Standard Deviation",	"Placebo",	"SD",	5.0,
"Primary analysis",	"trt comparison",	"Week 12 analysis",	"TRT - PBO",	"LMmean",	-0.3,
"Primary analysis",	"trt comparison",	"Week 12 analysis",	"TRT - PBO",	"LMstderr",	0.4
)


tfrmt(
  group = c(group, type),
  label = label, 
  column = column, 
  param = param, 
  values = value,
  body_plan = body_plan(
    frmt_structure(
      group_val = list(type = "description", group = ".default"), 
      label_val = ".default", frmt("xx.x")
    ), 
    frmt_structure(
      group_val = list(type = "trt comparison", group = ".default"), 
      label_val = ".default", 
      frmt_combine("{LMmean} ({LMstderr})",
                   `LMmean` = frmt("xx.x"),
                   `LMstderr` = frmt("xx.xx")
                   )
    )
  ),
  col_plan = col_plan(-type)
) %>% 
  print_to_gt(data)

```

But this would not have this on the same line like the example you showed. That is for two reasons 1) different groups are on different line and 2) different labels are on different rows. So to make the example you are looking at you would need to have a shared group and label, but use the param value to distinguish. 

```{r}

data2 <- tribble(
  ~group,	~label,	~column,	~param,	~value,
  "Primary analysis",	"Week 12 analysis",	"Placebo",	"mean",	79.0,
  "Primary analysis",	"Week 12 analysis",	"Placebo",	"SD",	5.0,
  "Primary analysis",	"Week 12 analysis",	"Treatment",	"mean",	82.0,
  "Primary analysis",	"Week 12 analysis",	"Treatment",	"SD",	6.0,
  "Primary analysis",	"Week 12 analysis",	"TRT - PBO",	"LMmean",	-0.3,
  "Primary analysis",	"Week 12 analysis",	"TRT - PBO",	"LMstderr",	0.4
)

tfrmt(
  group = group, 
  label = label, 
  column = column, 
  param = param, 
  value = value,
  body_plan = body_plan(
    frmt_structure(group_val = ".default", label_val = ".default",
                   frmt_combine("{mean}/{SD}",
                                mean = frmt("xx.x"),
                                SD = frmt("x.xx")
                   )
                   ),
    frmt_structure(group_val = ".default", label_val = ".default",
                   frmt_combine("{LMmean} ({LMstderr})",
                                LMmean = frmt("x.x"),
                                LMstderr = frmt("x.xx")
                   )
    )
  )
) %>% 
  print_to_gt(data2)
```

If these examples aren't what you mean please tell me. If you want I can set up a quick meeting so we can talk through this

**Comment by bailliem** [comment]
@statasaurus - this is what I was meaning and works to handle it this way withouth needing the additional variable.
