### ISSUE TITLE
Adding images folder to Rbuildignore

### ISSUE THREAD

**Issue by statasaurus** [GSK-Biostatistics/tfrmt#225]

**Comment by bzkrouse** [comment]
@karima662 and I noticed that pkgdown prefers them to be stored in /man/figures or /vignettes. So we do need to move them before excluded from the buildignore

**Comment by bzkrouse** [comment]
Update that we will keep example-related images in /images and vignette-related in /man/figures

**Comment by karima662** [comment]
images folder added to Rbuildignore in one of the last commits for pr #205
