### ISSUE TITLE
Handling extra columns in supplied dataset

### ISSUE THREAD

**Issue by thebioengineer** [GSK-Biostatistics/tfrmt#232]
We need to come up with a method for handling datasets with values that are not intended in the final table. One solution is to use col_plan, but we will need to move that up and changes where the complex point is in the data.

**Comment by statasaurus** [comment]
I don't understand. Yes I would use col_plan if people want to put them in, but there is a risk this will cause problems with the pivot's. In which cause I feel comfortable telling people they need to drop those column before. I  think if we do anything more complicated there will be too much complexity cost

**Comment by statasaurus** [comment]
I think it resolved with the new col_plan
