### ISSUE TITLE
Issue with frmt_combine when param values are [{0.95LCL}, {0.95UCL}]

### ISSUE THREAD

**Issue by statasaurus** [GSK-Biostatistics/tfrmt#365]

**Comment by bzkrouse** [comment]
In this case the user needs to surround the value with backticks and it should be good. This will also allow the user to have param names with spaces in them, etc.
```
frmt_combine(
  "[{`0.95 LCL`}, {`0.95 UCL`}]",
  `0.95 LCL` = frmt("x.x"),
  `0.95 UCL` = frmt("x.x")
)
```

**Comment by bzkrouse** [comment]
reopening as this seems to need fixing again. backticks will need to be removed prior to this line: https://github.com/GSK-Biostatistics/tfrmt/blob/main/R/apply_table_frmt_plan.R#L155
