### ISSUE TITLE
Improve error message when label is missing

### ISSUE THREAD

**Issue by bzkrouse** [GSK-Biostatistics/tfrmt#388]
For group-level summary rows, {tfrmt} expects group & label variables to have equal values. If the data is prepared with missing label values instead, current error message is the following:
![image](https://github.com/GSK-Biostatistics/tfrmt/assets/14199771/ca140596-a56f-441f-bc8f-b7fe31b07ce3)

Improve messaging to identify cases where label is NA and suggest they set group/label to be equal for group-level summaries

**Comment by bzkrouse** [comment]
"`label` column < column name > contains NA values. For group-level summary data, `label` and the relevant `group` values should match." or some variant :)

**Comment by karima662** [comment]
addressing in #442
