### ISSUE TITLE
Feature Request - Specify rounding method (ie halves round up vs round to even)

### ISSUE THREAD

**Issue by dereksonderegger** [GSK-Biostatistics/tfrmt#400]
One source of mis-alignment between SAS macros and R is that by default R does round-to-even while the default round macro in SAS does halves-round-up where up is larger in magnitude (i.e. away from zero).

It would be helpful, albeit probably way too much work for an edge case, to be able to specify what rounding procedure to use.

Background: I was asking Ellis about this issue at the Posit 2023 conference and he requested I open a feature request for this just to put it on peoples radar.

**Comment by bzkrouse** [comment]
Thanks for the suggestion! While providing different rounding options out-of-the-box is not currently within scope for the package, it is still possible for users to customize this! This is possible via the `frmt()` function's `transform` argument. Here, you can pass custom functions to be applied during the formatting step in conjunction with the "xx.x" notation. Example below, first with the default rounding, then with a custom rounding function from {janitor}:

```r
# create data
dat <- tibble::tribble(
  ~ group, ~label, ~column, ~param, ~value,
  "grp1" , "lbl1", "col1",  "mean", 1.250,
  "grp1" , "lbl2", "col1",  "mean", 1.350,
  "grp1" , "lbl1", "col2",  "mean", 1.750,
  "grp1" , "lbl2", "col2",  "mean", 1.450,
  "grp2" , "lbl1", "col1",  "mean", 1.050,
  "grp2" , "lbl2", "col1",  "mean", 1.850,
  "grp2" , "lbl1", "col2",  "mean", 1.950,
  "grp2" , "lbl2", "col2",  "mean", 1.650,
)

# default rounding
tfrmt(
  group=group,
  label=label,
  column=column,
  param=param,
  value=value,
  body_plan=body_plan(
    frmt_structure(group_val=".default",label_val=".default",
                   frmt("xx.x"))
  )
) %>% 
  print_to_gt(dat)

# custom rounding function
tfrmt(
  group=group,
  label=label,
  column=column,
  param=param,
  value=value,
  body_plan=body_plan(
    frmt_structure(group_val=".default",label_val=".default",
                   frmt("xx.x", transform= ~janitor::round_half_up(., digits=1)))
  )
) %>% 
  print_to_gt(dat)
```

I'm going to close the issue but I hope that helps! Let me know if you have any further questions or ideas!
