### ISSUE TITLE
Add argument to `print_mock_gt` and `print_to_gt` to not print messages

### ISSUE THREAD

**Issue by asbates** [GSK-Biostatistics/tfrmt#413]
It would be nice if `print_mock_gt` and `print_to_gt` had an option to not print messages. Maybe something like `verbose` or `chatty` where if the value is false, no messages get printed.

As an example use case,  I've been using `print_mock_gt` a lot for generating mock tables with no intention of adding data. The message `Message: 'tfrmt' will need 'value' value to 'print_to_gt' when data is avaliable` is nice to have at first but after a while it gets to be noisy.

I'm happy to submit a PR if this is something you'd like to add.

**Comment by bzkrouse** [comment]
Hi @asbates I am glad you are finding {tfrmt} useful for creating mocks. The vision of the mocks functionality is that the tfrmt object can later be applied to study data with values. That being said, we want users to be aware of pieces that are missing now and required later on.  In general, with both `print_to_gt` and `print_mock_gt`, console messages are our primary way of informing users when something is missing or not quite right in the tfrmt object, so we feel it is important to keep these visible. 
However I really appreciate this suggestion and for you offering a contribution! In lieu of an option within the function, you can try using a utility like `suppressMessages()` or `purrr::quietly()` to quiet the messages, but let me know if there are any issues with those.

**Comment by asbates** [comment]
Thanks @bzkrouse that makes sense. I'll go ahead and close this issue.
