### ISSUE TITLE
put RTF footnotes in the document footer by default

### ISSUE THREAD

**Issue by bzkrouse** [GSK-Biostatistics/tfrmt#422]
Add this to the existing series of `tab_options` within the `print_to_gt` function: `tab_options(page.footer.use_tbl_notes = TRUE)`

This will get picked up if gt exports the table to an RTF document, but ignored otherwise.

**Comment by alanahjonas95** [comment]
@bzkrouse does this option need to be added to the function cleaned_data_to_gt.default from line 251 there is a long list of tab_options there?

**Comment by bzkrouse** [comment]
@alanahjonas95 Yup, exactly!
