### ISSUE TITLE
Layering body style unique values

### ISSUE THREAD

**Issue by thebioengineer** [GSK-Biostatistics/tfrmt#63]
Currently the code calls:

`unique(c(x_body_style,y_body_style))` to get the combined set of body styles when layering. 

I was thinking due to the way that we apply formats, if there is duplications, we would want to keep the second copy? 

Thoughts?

**Comment by statasaurus** [comment]
Will this mess with the order? I think I might need more context to fully understand it. But it is the only thing I would be worried about
