### ISSUE TITLE
col align for group and label variables

### ISSUE THREAD

**Issue by bzkrouse** [GSK-Biostatistics/tfrmt#89]

**Comment by thebioengineer** [comment]
Do we want to allow character alignment as well for non-data columns? This could be addressed in #220

**Comment by thebioengineer** [comment]
Can we chat about this tomorrow? Been working on this, and there may be slight conflicts with row_grp_plan and the handling of groups/etc.

**Comment by statasaurus** [comment]
@thebioengineer this is merged in right?

**Comment by thebioengineer** [comment]
Yes, it has been :+1:
